Repository boostcampwm2023/web10-Lesser, pull requests merged in 2023-12, with the labels that each got.

#92 refactor: hooks 폴더 구조를 세분화 및 react-query의 커스텀 훅을 위한 폴더 구조 생성
  FE/src/components/backlog/BacklogTitle.tsx
  FE/src/components/backlog/EpicComponent.tsx
  FE/src/components/backlog/PostButton.tsx
  FE/src/components/backlog/StoryComponent.tsx
  FE/src/components/common/SideNavigationBar.tsx
  FE/src/hooks/pages/backlog/useDetail.tsx
  FE/src/hooks/pages/backlog/usePostBacklog.tsx
  FE/src/hooks/pages/backlog/useToggleButton.tsx
  FE/src/hooks/pages/backlog/useUpdateBacklog.tsx
  FE/src/hooks/pages/project/useProjectForm.tsx
  FE/src/hooks/pages/useKanbanDrag.tsx
  FE/src/hooks/pages/useLogin.tsx
  FE/src/hooks/pages/useLogout.tsx
  FE/src/hooks/queries/.gitkeep
  FE/src/pages/LoginPage.tsx
  FE/src/pages/ProjectCreatePage.tsx
  FE/src/pages/ProjectPage.tsx
Labels: FE

#91 스프린트 종료 API, 진행중인 스프린트 조회 API 수정
  BE/src/projects/dto/GetSprintProgressRequest.dto.ts
  BE/src/projects/projects.service.ts
  BE/src/sprints/dto/Sprint.dto.ts
  BE/src/sprints/sprints.controller.ts
  BE/src/sprints/sprints.service.ts
Labels: BE

#94 회고글 작성시 srintId, content 값을 받도록 수정
  BE/src/reviews/dto/Review.dto.ts
Labels: 🔨fix

#95 회원 닉네임(username)으로 조회하는 API 구현
  BE/src/common/types/githubResource.type.ts
  BE/src/members/dto/github-user.dto.ts
  BE/src/members/dto/member.dto.ts
  BE/src/members/members.controller.ts
  BE/src/members/members.service.ts
Labels: BE

#97 프로젝트 조회시 멤버정보로 깃허브 아이디 반환, 프로젝트 생성시 멤버리스트 함께 요청받음
  BE/src/projects/dto/Project.dto.ts
  BE/src/projects/projects.service.ts
Labels: 🔨fix

#99 회고란 탭 기능 구현
  FE/src/components/review/DonutChart.tsx
  FE/src/components/review/ReviewChart.tsx
  FE/src/components/review/ReviewHeader.tsx
  FE/src/components/review/ReviewReminiscing.tsx
  FE/src/components/review/ReviewSprint.tsx
  FE/src/hooks/pages/review/useReminiscing.tsx
  FE/src/pages/ReviewPage.tsx
  FE/src/types/review.ts
  FE/src/utils/date.ts
Labels: FE, 🔨fix

#98 프로젝트 회원 추가 API 구현
  BE/src/members/dto/member.dto.ts
  BE/src/projects/dto/Project.dto.ts
  BE/src/projects/projects.controller.ts
  BE/src/projects/projects.service.ts
Labels: BE

#107 백로그 설명 페이지 구현
  FE/src/App.tsx
  FE/src/assets/images/backlog-landing.png
  FE/src/assets/images/sprint-landing.png
  FE/src/pages/BacklogPage.tsx
  FE/src/pages/backlog/BacklogLandingPage.tsx
  FE/src/pages/backlog/BacklogPage.tsx
Labels: FE

#108 사용자의 본인의 정보를 프로젝트 생성 시, 참여자에 자동으로 추가하는 로직을 작성
  FE/src/components/project/ProjectCard.tsx
  FE/src/components/project/ProjectInviteForm.tsx
  FE/src/constants/constants.tsx
  FE/src/hooks/pages/project/useCreateNewProject.ts
  FE/src/hooks/pages/project/useSearchUsername.ts
  FE/src/hooks/queries/project/usePostNewProject.ts
Labels: FE, 🔨fix

#113 스프린트 생성 시 태스크 설정 기능, 칸반보드, 스프린트 종료
  FE/src/apis/sprint/fetchPatchSprintEnd.ts
  FE/src/components/sprint/FilterDropdown.tsx
  FE/src/components/sprint/KanbanBoard.tsx
  FE/src/components/sprint/modal/SprintEndModal.tsx
  FE/src/components/sprint/sprintCreate/SprintBacklogComponent.tsx
  FE/src/components/sprint/sprintCreate/SprintBacklogSetting.tsx
  FE/src/hooks/queries/sprint/index.ts
  FE/src/hooks/queries/sprint/useGetProgressSprint.ts
  FE/src/hooks/queries/sprint/usePatchSprintEnd.ts
  FE/src/hooks/queries/sprint/usePatchTaskState.ts
  FE/src/pages/SprintPage.tsx
  FE/src/pages/sprint/SprintCreatePage.tsx
  FE/src/types/sprint.ts
Labels: FE

#128 feat: [sprint-create] 스프린트 종료일 설정 기능 구현
  FE/src/components/sprint/sprintCreate/SprintGoalSetting.tsx
Labels: FE

#152 Refresh token 발급 로직에 회원 id 추가
  BE/src/common/lesser-jwt/lesser-jwt.service.ts
  BE/src/members/members.service.ts
Labels: BE, 🔨fix

#157 필터링 동작 수정, 로딩 컴포넌트 생성
  FE/src/assets/images/loading-image.png
  FE/src/components/common/Loading.tsx
  FE/src/components/sprint/TaskCard.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/SprintPage.tsx
  FE/src/types/sprint.ts
Labels: FE, 🔨fix

#160 로그인 화면 크기 조정, 스프린트 페이지 오류 수정
  FE/src/components/common/Loading.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/SprintPage.tsx
Labels: FE, 🔨fix
