Repository boostcampwm2023/web10-Lesser, pull requests merged in 2023-11, with the labels that each got.

#1 NEST초기 환경설정
  BE/.eslintrc.js
  BE/.gitignore
  BE/.prettierrc
  BE/README.md
  BE/nest-cli.json
  BE/package-lock.json
  BE/package.json
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/backlogs/backlogs.controller.spec.ts
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.module.ts
  BE/src/backlogs/backlogs.service.spec.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/entities/epic.entity.ts
  BE/src/entities/member-project.entity.ts
  BE/src/entities/member.entity.ts
  BE/src/entities/project.entity.ts
  BE/src/entities/review.entity.ts
  BE/src/entities/sprint.entity.ts
  BE/src/entities/story.entity.ts
  BE/src/entities/task-sprint.entity.ts
  BE/src/entities/task.entity.ts
  BE/src/main.ts
  BE/src/members/members.controller.spec.ts
  BE/src/members/members.controller.ts
  BE/src/members/members.module.ts
  BE/src/members/members.service.spec.ts
  BE/src/members/members.service.ts
  BE/src/projects/projects.controller.spec.ts
  BE/src/projects/projects.controller.ts
  BE/src/projects/projects.module.ts
  BE/src/projects/projects.service.spec.ts
  BE/src/projects/projects.service.ts
  BE/src/reviews/reviews.controller.spec.ts
  BE/src/reviews/reviews.controller.ts
  BE/src/reviews/reviews.module.ts
  BE/src/reviews/reviews.service.spec.ts
  BE/src/reviews/reviews.service.ts
  BE/src/sprints/sprints.controller.spec.ts
  BE/src/sprints/sprints.controller.ts
  BE/src/sprints/sprints.module.ts
  BE/src/sprints/sprints.service.spec.ts
  BE/src/sprints/sprints.service.ts
  BE/test/app.e2e-spec.ts
  BE/test/jest-e2e.json
  BE/tsconfig.build.json
  BE/tsconfig.json
Labels: BE

#6 칸반보드를 확인하는 스프린트 페이지 코드 작성
  FE/src/components/common/ProgressBar/ProgressBar.tsx
  FE/src/components/sprint/ColumnBoard.tsx
  FE/src/components/sprint/KanbanBoard.tsx
  FE/src/components/sprint/TaskCard.tsx
  FE/src/pages/sprint/SprintPage.tsx
Labels: FE

#7 태스크 생성
  BE/src/app.module.ts
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.module.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/dto/create-backlogs-epic.dto.ts
  BE/src/dto/create-backlogs-story.dto.ts
  BE/src/dto/create-backlogs-task.dto.ts
  BE/src/entities/story.entity.ts
  BE/src/entities/task.entity.ts
Labels: BE

#10 백로그 페이지 코드 작성
  FE/src/components/backlog/EpicBlock.tsx
  FE/src/components/backlog/StoryBlock.tsx
  FE/src/components/backlog/TaskBlock.tsx
  FE/src/components/backlog/TaskModal.tsx
  FE/src/hooks/useBlock.tsx
  FE/src/pages/backlog/BacklogPage.tsx
Labels: FE

#13 백로그 API 수정, 백로그 테스트코드 작성
  BE/package.json
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/dto/create-backlogs-epic-response.dto.ts
  BE/src/dto/create-backlogs-story-response.dto.ts
  BE/src/dto/create-backlogs-task-response.dto.ts
  BE/test/app.e2e-spec.ts
  BE/test/jest-e2e.json
Labels: BE

#14 백로그 페이지 오류 수정
  FE/src/assets/fonts/PretendardVariable.woff2
  FE/src/assets/icons/calendar.svg
  FE/src/assets/icons/chart.svg
  FE/src/assets/icons/check.svg
  FE/src/assets/icons/checkbox.svg
  FE/src/assets/icons/chevron-down.svg
  FE/src/assets/icons/chevron-left.svg
  FE/src/assets/icons/chevron-right.svg
  FE/src/assets/icons/chevron-up.svg
  FE/src/assets/icons/closed.svg
  FE/src/assets/icons/doc.svg
  FE/src/assets/icons/edit.svg
  FE/src/assets/icons/minus.svg
  FE/src/assets/icons/plus.svg
  FE/src/assets/icons/uncheckbox.svg
  FE/src/components/backlog/BlockFrom.tsx
  FE/src/components/backlog/EpicBlock.tsx
  FE/src/components/backlog/StoryBlock.tsx
  FE/src/components/backlog/TaskModal.tsx
  FE/src/hooks/useBlock.tsx
  FE/src/index.css
  FE/src/pages/backlog/BacklogPage.tsx
  FE/tailwind.config.js
Labels: FE

#16 POST api/project 작성
  BE/.eslintrc.js
  BE/src/app.module.ts
  BE/src/backlogs/backlogs.module.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/backlogs/entities/epic.entity.ts
  BE/src/projects/dto/Project.dto.ts
  BE/src/projects/entity/project.entity.ts
  BE/src/projects/projects.controller.ts
  BE/src/projects/projects.module.ts
  BE/src/projects/projects.service.ts
  BE/test/backlogs.e2e-spec.ts
  BE/test/jest-e2e.json
  BE/test/projects.e2e-spec.ts
Labels: BE

#19 백엔드 서버 import 경로 오타 수정
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.service.ts
Labels: BE

#20 백로그 확인 API 작성 (/api/backlogs/{projectId})
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/backlogs/dto/backlog.dto.ts
  BE/test/backlogs.e2e-spec.ts
Labels: BE

#22 Task Modal 구현
  FE/src/assets/icons/CheckIcon.tsx
  FE/src/assets/icons/ChevronDownIcon.tsx
  FE/src/assets/icons/ChevronRightIcon.tsx
  FE/src/assets/icons/ClosedIcon.tsx
  FE/src/assets/icons/EditIcon.tsx
  FE/src/assets/icons/PlusIcon.tsx
  FE/src/components/backlog/BlockFrom.tsx
  FE/src/components/backlog/EpicBlock.tsx
  FE/src/components/backlog/StoryBlock.tsx
  FE/src/components/backlog/TaskBlock.tsx
  FE/src/components/backlog/TaskModal.tsx
  FE/src/hooks/useBlock.tsx
  FE/src/pages/backlog/BacklogPage.tsx
  FE/src/types/backlog.ts
  FE/src/types/icon.ts
  FE/tailwind.config.js
Labels: FE

#21 페이지 이동 네비게이션 바 생성
  FE/src/assets/icons/lesserLogo.svg
  FE/src/components/backlog/NavigationButton.tsx
  FE/src/components/backlog/SideNavigationBar.tsx
  FE/src/types/navigation.ts
Labels: FE

#25 네비게이션 바 적용
  FE/src/components/backlog/NavigationButton.tsx
  FE/src/components/backlog/SideNavigationBar.tsx
  FE/src/components/sprint/BoardHeader.tsx
  FE/src/components/sprint/ColumnBoard.tsx
  FE/src/components/sprint/KanbanBoard.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/SprintPage.tsx
  FE/src/pages/sprint/SprintPage.tsx
  FE/src/types/sprint.ts
Labels: FE

#26 내 프로젝트 화면 구성
  FE/src/App.tsx
  FE/src/assets/.gitkeep
  FE/src/assets/images/cross.png
  FE/src/components/project/ProjectCard.tsx
  FE/src/constants/.gitkeep
  FE/src/constants/constants.tsx
  FE/src/hooks/.gitkeep
  FE/src/pages/ProjectCreatePage.tsx
  FE/src/pages/ProjectPage.tsx
  FE/src/types/project.ts
  FE/tailwind.config.js
Labels: FE

#27 태스크 제목 편집 및 수정
  FE/src/components/backlog/BlockFrom.tsx
  FE/src/components/backlog/EpicBlock.tsx
  FE/src/components/backlog/StoryBlock.tsx
  FE/src/components/backlog/TaskBlock.tsx
  FE/src/components/backlog/TaskModal.tsx
  FE/src/hooks/useBlock.tsx
  FE/src/pages/BacklogPage.tsx
  FE/src/pages/backlog/BacklogPage.tsx
Labels: FE

#30 ProjectPage 리팩토링 : tag 종류 변경
  FE/src/components/project/ProjectCard.tsx
  FE/src/pages/ProjectCreatePage.tsx
  FE/src/pages/ProjectPage.tsx
Labels: FE

#31 칸반보드 및 네비게이션 바 디자인 수정
  FE/src/components/backlog/NavigationButton.tsx
  FE/src/components/backlog/SideNavigationBar.tsx
  FE/src/components/sprint/BoardHeader.tsx
  FE/src/components/sprint/ColumnBoard.tsx
  FE/src/components/sprint/TaskCard.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/SprintPage.tsx
Labels: FE

#32 /api/backlogs 기존 프로젝트 읽기 API작성
  BE/src/projects/dto/Project.dto.ts
  BE/src/projects/entity/project.entity.ts
  BE/src/projects/projects.controller.ts
  BE/src/projects/projects.service.ts
Labels: BE

#36 프로젝트 생성 코드 작성
  FE/src/apis/.gitkeep
  FE/src/apis/api.ts
  FE/src/components/project/ProjectCreateForm.tsx
  FE/src/components/project/ProjectProcessText.tsx
  FE/src/hooks/useProjectForm.tsx
  FE/src/pages/ProjectCreatePage.tsx
  FE/tailwind.config.js
Labels: FE

#42 로그인 확인가드
  BE/src/app.module.ts
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.module.ts
  BE/src/common/auth/IsLogin.guard.ts
  BE/src/common/auth/ProjectAccessGuard.guard.ts
  BE/src/common/auth/auth.guard.spec.ts
  BE/src/common/auth/auth.module.ts
  BE/src/projects/projects.controller.ts
  BE/src/projects/projects.module.ts
Labels: BE

#46 백로그 API 연동
  FE/.eslintrc
  FE/src/components/backlog/EpicBlock.tsx
  FE/src/components/backlog/StoryBlock.tsx
  FE/src/components/backlog/TaskBlock.tsx
  FE/src/components/backlog/TaskModal.tsx
  FE/src/hooks/useBlock.tsx
  FE/src/pages/BacklogPage.tsx
  FE/src/types/backlog.ts
Labels: FE

#53 백엔드 리팩토링
  BE/src/backlogs/backlogs.service.ts
  BE/src/backlogs/dto/backlog.dto.ts
  BE/src/main.ts
  BE/src/projects/projects.service.ts
Labels: BE

#55 로그인 회원 정보를 메모리에 저장, 로그아웃 및 토큰 리프레쉬 구현
  BE/src/members/dto/tokens.dto.ts
  BE/src/members/members.controller.ts
  BE/src/members/members.service.ts
Labels: BE

#57 로그인 로직 수정
  FE/src/apis/api.ts
Labels: FE, 🔨fix

#63 프로젝트, 백로그 유저 인가
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.module.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/backlogs/backlogsAuth.service.ts
  BE/src/members/entities/member.entity.ts
  BE/src/projects/entity/project.entity.ts
  BE/src/projects/projects.controller.ts
  BE/src/projects/projects.service.ts
Labels: BE

#65 feat: [backlog-read] 백로그 중복권한체크 제거
  BE/src/backlogs/backlogs.controller.ts
  BE/src/backlogs/backlogs.service.ts
Labels: BE

#62 칸반보드 드래그 앤 드롭 구현
  FE/src/components/sprint/ColumnBoard.tsx
  FE/src/components/sprint/KanbanBoard.tsx
  FE/src/components/sprint/TaskCard.tsx
  FE/src/data/sprint.json
  FE/src/hooks/useKanbanDrag.tsx
  FE/src/pages/SprintPage.tsx
  FE/src/types/sprint.ts
Labels: FE

#64 로그아웃 구현
  FE/src/apis/api.ts
  FE/src/components/common/NavigationButton.tsx
  FE/src/components/common/SideNavigationBar.tsx
  FE/src/constants/constants.tsx
  FE/src/hooks/useLogin.tsx
  FE/src/hooks/useLogout.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/ProjectPage.tsx
Labels: FE

#67 회고 페이지 레이아웃 작성
  FE/src/components/review/DonutChart.tsx
  FE/src/components/review/ReviewChart.tsx
  FE/src/components/review/ReviewHeader.tsx
  FE/src/components/review/ReviewReminiscing.tsx
  FE/src/components/review/ReviewSprint.tsx
  FE/src/index.css
  FE/src/pages/ReviewPage.tsx
Labels: FE

#68 스프린트 생성 API, 회고 생성 API
  BE/src/app.module.ts
  BE/src/entities/review.entity.ts
  BE/src/entities/sprint.entity.ts
  BE/src/reviews/dto/Review.dto.ts
  BE/src/reviews/entities/review.entity.ts
  BE/src/reviews/reviews.controller.ts
  BE/src/reviews/reviews.module.ts
  BE/src/reviews/reviews.service.ts
  BE/src/sprints/dto/Sprint.dto.ts
  BE/src/sprints/entities/sprint.entity.ts
  BE/src/sprints/sprints.controller.ts
  BE/src/sprints/sprints.module.ts
  BE/src/sprints/sprints.service.ts
Labels: BE

#69 프로젝트, 백로그 API를 멤버와 연동
  BE/src/backlogs/backlogs.module.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/backlogs/dto/backlog.dto.ts
  BE/src/backlogs/dto/baseType.dto.ts
  BE/src/backlogs/entities/task.entity.ts
  BE/src/common/decorators/IsNullOrIntDecorator.ts
  BE/src/projects/dto/Project.dto.ts
  BE/src/projects/projects.service.ts
Labels: BE

#71 스프린트 생성 API 구현 - 스프린트는 다수의 태스크 포함
  BE/src/backlogs/dto/Task.dto.ts
  BE/src/backlogs/entities/task.entity.ts
  BE/src/entities/task-sprint.entity.ts
  BE/src/sprints/dto/Sprint.dto.ts
  BE/src/sprints/entities/sprint-task.entity.ts
  BE/src/sprints/entities/sprint.entity.ts
  BE/src/sprints/sprints.controller.ts
  BE/src/sprints/sprints.module.ts
  BE/src/sprints/sprints.service.ts
Labels: BE

#72 백로그 sequence 데이터 추가
  BE/src/backlogs/backlogs.module.ts
  BE/src/backlogs/backlogs.service.ts
  BE/src/backlogs/dto/Epic.dto.ts
  BE/src/backlogs/dto/Story.dto.ts
  BE/src/backlogs/dto/Task.dto.ts
  BE/src/backlogs/dto/backlog.dto.ts
  BE/src/backlogs/dto/baseType.dto.ts
  BE/src/backlogs/entities/epic.entity.ts
  BE/src/backlogs/entities/story.entity.ts
  BE/src/backlogs/entities/task.entity.ts
  BE/src/projects/entity/projectCounter.entity.ts
  BE/src/projects/projects.module.ts
  BE/src/projects/projects.service.ts
Labels: BE

#73 회고 페이지 번다운 차트 구현
  FE/package.json
  FE/src/assets/icons/ChevronDownIcon.tsx
  FE/src/components/review/ReviewChart.tsx
  FE/src/components/review/ReviewHeader.tsx
  FE/src/components/review/ReviewSprint.tsx
  FE/src/components/review/ReviewSprintInfo.tsx
  FE/yarn.lock
Labels: FE

#74 회고 페이지 조회 API 작성
  BE/src/reviews/dto/Review.dto.ts
  BE/src/reviews/dto/SprintReviewResponse.dto.ts
  BE/src/reviews/reviews.controller.ts
  BE/src/reviews/reviews.module.ts
  BE/src/reviews/reviews.service.ts
  BE/src/sprints/entities/sprint-task.entity.ts
Labels: BE

#81 스프린트 정보와 차트 API 연동
  FE/src/App.tsx
  FE/src/components/common/SideNavigationBar.tsx
  FE/src/components/review/DonutChart.tsx
  FE/src/components/review/ReviewChart.tsx
  FE/src/components/review/ReviewHeader.tsx
  FE/src/components/review/ReviewSprint.tsx
  FE/src/data/review.json
  FE/src/main.tsx
  FE/src/pages/ReviewPage.tsx
  FE/src/types/review.ts
Labels: FE

#86 fix : review 페이지 path 수정
  FE/src/App.tsx
Labels: 🔨fix
