Repository boostcampwm2023/web10-Lesser, pull requests merged in 2024-03, with the labels that each got.

#214 feat: 개발서버가 다른 origin에 대해 CORS 허용하도록 수정
  backend/src/main.ts
Labels: BE, 🎉feature

#216 fix: 컨트롤러의 refresh메서드에서 리프레시토큰이 유효하지 않은 JWT토큰일때 401에러 반환하도록 수정(기존 : 500)
  backend/src/auth/controller/auth.controller.spec.ts
  backend/src/auth/controller/auth.controller.ts
Labels: BE, 🔨fix

#220 feat: Member 엔티티 제약조건 설정
  backend/src/member/entity/member.entity.ts
Labels: BE, 🎉feature

#225 feat: 개발서버 및 프로덕션서버 HTTPS 적용
  docker-compose.dev.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/Dockerfile.dev
  nginx/Dockerfile.prod
  nginx/conf/conf.d/dev.conf
  nginx/conf/conf.d/prod.conf
Labels: BE, 🎉feature

#229 fix: 깃허브 유저네임 API의 HTTP 메서드를 GET으로 수정
  backend/src/auth/controller/auth.controller.ts
Labels: BE, 🔨fix

#235 feat: debounce를 이용한 닉네임 중복검사 및 회원가입 API 연결
  frontend/src/apis/api/signupAPI.ts
  frontend/src/components/account/NicknameInput.tsx
  frontend/src/components/account/PositionInput.tsx
  frontend/src/components/account/SignupMainSection.tsx
  frontend/src/components/account/TechStackInput.tsx
  frontend/src/components/account/TechStackModal.tsx
  frontend/src/constants/path.ts
  frontend/src/hooks/common/useDebounce.tsx
  frontend/src/test/useDebounce.test.tsx
  frontend/src/test/useDropdown.test.tsx
  frontend/src/types/authDTO.ts
Labels: FE, 🎉feature

#237 [feat] error boundary 적용하기
  frontend/package.json
  frontend/src/AppRouter.tsx
  frontend/src/GlobalErrorBoundary.tsx
  frontend/src/constants/path.ts
  frontend/src/pages/ErrorThrowPage.tsx
  frontend/src/pages/TempHomepage.tsx
  frontend/src/pages/error/ErrorPage.tsx
  frontend/src/pages/index.ts
  frontend/yarn.lock
Labels: FE, 🎉feature

#245 fix: 쿠키 path 경로 수정
  backend/src/auth/controller/auth.controller.spec.ts
  backend/src/auth/controller/auth.controller.ts
Labels: 🔨fix

#243 feat: 프로젝트 목록 페이지 구현
  frontend/jest.config.cjs
  frontend/src/apis/api/loginAPI.ts
  frontend/src/apis/api/projectAPI.ts
  frontend/src/apis/api/signupAPI.ts
  frontend/src/apis/utils/authAPI.ts
  frontend/src/components/projects/ProjectCard.tsx
  frontend/src/components/projects/ProjectList.tsx
  frontend/src/components/projects/ProjectsSideBar.tsx
  frontend/src/components/projects/index.ts
  frontend/src/constants/path.ts
  frontend/src/constants/projects.ts
  frontend/src/hooks/common/dropdown/useDropdown.tsx
  frontend/src/pages/projects/ProjectsPage.tsx
  frontend/src/test/projectSortingTest.test.tsx
  frontend/src/types/projectDTO.ts
  frontend/src/utils/formatDate.ts
  frontend/src/utils/projectSortByOption.ts
  frontend/svgTransformer.cjs
Labels: FE, 🎉feature

#247 feat : 로그인 상태에 따른 에러 처리 코드 & PrivateRoute, PublicRoute 개발
  frontend/src/AppRouter.tsx
  frontend/src/GlobalErrorBoundary.tsx
  frontend/src/apis/api/loginAPI.ts
  frontend/src/apis/utils/authAPI.ts
  frontend/src/components/common/route/PrivateRoute.tsx
  frontend/src/components/common/route/PublicRoute.tsx
  frontend/src/components/common/route/RouteLoading.tsx
  frontend/src/components/login/LoginCardSection.tsx
  frontend/src/pages/ErrorThrowPage.tsx
  frontend/src/pages/TempHomepage.tsx
  frontend/src/pages/error/AuthErrorPage.tsx
  frontend/src/pages/error/CommonErrorPage.tsx
  frontend/src/pages/error/ErrorPage.tsx
  frontend/src/pages/index.ts
  frontend/src/types/authDTO.ts
  frontend/src/utils/route/checkAuthentication.ts
Labels: FE, 🎉feature

#249 feat : 외부 signup 페이지 접근 제한 코드 작성
  frontend/src/GlobalErrorBoundary.tsx
  frontend/src/apis/api/loginAPI.ts
  frontend/src/constants/error.ts
  frontend/src/constants/path.ts
  frontend/src/pages/TempHomepage.tsx
  frontend/src/pages/account/SignupPage.tsx
  frontend/src/pages/error/NotPermittedPage.tsx
Labels: FE, 🔨fix, 🎉feature
