Repository boostcampwm2023/web10-Lesser, pull requests merged in 2024-02, with the labels that each got.

#198 chore: React-Router 적용
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/pages/TempHomepage.tsx
  frontend/src/pages/index.ts
  frontend/yarn.lock
Labels: FE

#201 feat: 로그인이 되어있지 않은 유저에게 tempId토큰 반환하는 기능 구현
  .github/workflows/dev.cd.yml
  .github/workflows/dev.ci.yml
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/controller/auth.controller.spec.ts
  backend/src/auth/controller/auth.controller.ts
  backend/src/auth/entity/tempMember.entity.ts
  backend/src/auth/repository/tempMember.repository.ts
  backend/src/auth/service/auth.service.spec.ts
  backend/src/auth/service/auth.service.ts
  backend/src/auth/service/dto/github-user.dto.ts
  backend/src/github-api/github-api.module.ts
  backend/src/github-api/github-api.service.ts
  backend/src/lesser-config/constants.ts
  backend/src/lesser-config/lesser-config.module.spec.ts
  backend/src/lesser-config/lesser-config.module.ts
  backend/src/lesser-jwt/lesser-jwt.module.ts
  backend/src/lesser-jwt/lesser-jwt.service.spec.ts
  backend/src/lesser-jwt/lesser-jwt.service.ts
  backend/src/member.entity.ts
  backend/src/member/entity/member.entity.ts
  backend/src/member/member.module.ts
  backend/src/member/repository/member.repository.ts
  backend/src/member/service/member.service.ts
Labels: BE, 🎉feature

#200 feat: login 페이지 컴포넌트 구현
  frontend/coverage/clover.xml
  frontend/coverage/lcov-report/index.html
  frontend/coverage/lcov-report/mocks/handlers.ts.html
  frontend/coverage/lcov-report/mocks/index.html
  frontend/coverage/lcov-report/mocks/node.ts.html
  frontend/coverage/lcov-report/utils/index.html
  frontend/coverage/lcov-report/utils/sampleFunction.ts.html
  frontend/src/assets/Logo.svg
  frontend/src/assets/github-mark-white.svg
  frontend/src/constants/login.ts
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/TempHomepage.tsx
  frontend/tailwind.config.js
Labels: FE, 🎉feature

#203 feat: /api/auth/github/authentication API 구현
  backend/src/auth/controller/auth.controller.spec.ts
  backend/src/auth/controller/auth.controller.ts
  backend/src/auth/service/auth.service.spec.ts
  backend/src/auth/service/auth.service.ts
  backend/src/lesser-jwt/lesser-jwt.service.spec.ts
  backend/src/lesser-jwt/lesser-jwt.service.ts
  backend/src/member/service/member.service.ts
Labels: BE, 🎉feature

#196 feat: 드롭다운 기능 구현
  frontend/package.json
  frontend/src/common/dropdown/useDropdown.test.tsx
  frontend/src/common/dropdown/useDropdown.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers.ts
Labels: FE, 🎉feature

#211 refactor: 중복된 변수명 accessToken 중 깃허브의 액세스 토큰명을 githubAccessToken으로 변경
  backend/src/auth/service/auth.service.ts
Labels: BE, refactor

#209 feat: 모달 생성 모듈, 회원가입 화면 구현
  frontend/src/assets/icons/chevron-down.svg
  frontend/src/assets/icons/closed.svg
  frontend/src/assets/icons/plus.svg
  frontend/src/common/modal/ModalProvider.tsx
  frontend/src/common/modal/useModal.tsx
  frontend/src/components/account/JobInput.tsx
  frontend/src/components/account/NextStepButton.tsx
  frontend/src/components/account/NicknameInput.tsx
  frontend/src/components/account/SignupSideBar.tsx
  frontend/src/components/account/TechStackInput.tsx
  frontend/src/components/account/TechStackModal.tsx
  frontend/src/components/common/CategoryButton.tsx
  frontend/src/constants/account.ts
  frontend/src/main.tsx
  frontend/src/pages/account/SignupPage.tsx
  frontend/src/pages/index.ts
  frontend/src/test/useModal.test.tsx
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: FE, 🎉feature
