Repository boostcampwm2023/web10-Lesser, pull requests merged in 2024-05, with the labels that each got.

#273 feat : 클라이언트에서 웹소켓 연결시 액세스 토큰 보내기
  frontend/src/AppRouter.tsx
  frontend/src/apis/utils/authAPI.ts
  frontend/src/hooks/common/socket/useSocket.ts
Labels: FE, 🔨fix

#274 fix : Modal Z-index 수정
  frontend/src/components/landing/LandingLinkModal.tsx
Labels: FE, 🔨fix

#277 feat : LandingMemoList UI 완성
  frontend/src/assets/icons/trash-can.svg
  frontend/src/components/landing/common/LandingTitleUI.tsx
  frontend/src/components/landing/link/LandingLink.tsx
  frontend/src/components/landing/link/LandingLinkBlock.tsx
  frontend/src/components/landing/link/LandingLinkModal.tsx
  frontend/src/components/landing/member/LandingMember.tsx
  frontend/src/components/landing/member/UserBlock.tsx
  frontend/src/components/landing/memo/LandingMemoList.tsx
  frontend/src/components/landing/memo/MemoBlock.tsx
  frontend/src/components/landing/memo/MemoColorButton.tsx
  frontend/src/components/landing/memo/MemoEditor.tsx
  frontend/src/components/landing/project/LandingProject.tsx
  frontend/src/components/landing/project/LandingProjectLink.tsx
  frontend/src/components/landing/sprint/LandingSprint.tsx
  frontend/src/components/landing/sprint/LandingSprintBar.tsx
  frontend/src/hooks/common/landing/useLandingMemo.tsx
  frontend/src/hooks/common/socket/useLandingSocket.ts
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/types/DTO/landingDTO.ts
  frontend/src/types/common/landing.ts
Labels: FE, 🎉feature, ♻️ refactor

#278 fix: 메모 생성 API 버그수정 및 회귀 테스트 추가
  backend/src/project/dto/MemoCreateRequest.dto.ts
  backend/src/project/entity/memo.entity.ts
  backend/test/project/ws-memo.e2e-spec.ts
Labels: BE, 🔨fix, 🍐pair programming

#281 feat : 메모 생성 및 삭제 기능 완성
  frontend/src/components/landing/memo/LandingMemoList.tsx
  frontend/src/components/landing/memo/MemoBlock.tsx
  frontend/src/components/landing/memo/MemoColorButton.tsx
  frontend/src/components/landing/memo/MemoEditor.tsx
  frontend/src/hooks/common/socket/useLandingEmitEvent.ts
  frontend/src/hooks/common/socket/useLandingSocket.ts
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/types/common/landing.ts
Labels: FE, 🎉feature, ♻️ refactor

#283 feat: 회원가입 페이지에서 마우스 휠로 단계를 넘어가는 기능
  frontend/src/components/account/NicknameInput.tsx
  frontend/src/components/account/PositionInput.tsx
  frontend/src/components/account/SignupMainSection.tsx
  frontend/src/components/account/TechStackInput.tsx
  frontend/src/components/account/TechStackModal.tsx
  frontend/src/hooks/common/dropdown/useDropdown.tsx
  frontend/src/hooks/pages/account/useWheelDown.ts
  frontend/src/hooks/pages/account/useWheelUp.ts
Labels: FE, 🎉feature
