Repository boostcampwm2023/web10-Lesser, pull requests merged in 2024-08, with the labels that each got.

#321 feat: 스토리 드래그 앤 드롭 기능, 에픽별 백로그 페이지 구현
  frontend/package.json
  frontend/src/AppRouter.tsx
  frontend/src/components/backlog/EpicBlock.tsx
  frontend/src/components/backlog/EpicDropdown.tsx
  frontend/src/components/backlog/StoryBlock.tsx
  frontend/src/components/backlog/StoryCreateForm.tsx
  frontend/src/components/backlog/TaskCreateBlock.tsx
  frontend/src/components/backlog/TaskCreateForm.tsx
  frontend/src/hooks/pages/backlog/useEpicEmitEvent.ts
  frontend/src/hooks/pages/backlog/useStoryEmitEvent.ts
  frontend/src/hooks/pages/backlog/useTaskEmitEvent.ts
  frontend/src/pages/backlog/EpicPage.tsx
  frontend/src/pages/backlog/FinishedStoryPage.tsx
  frontend/src/pages/backlog/UnfinishedStoryPage.tsx
  frontend/src/types/DTO/backlogDTO.ts
  frontend/src/types/common/backlog.ts
  frontend/src/utils/changeEpicListToStoryList.ts
  frontend/src/utils/getDragElementIndex.ts
  frontend/yarn.lock
Labels: FE, 🎉feature

#323 fix: 스토리 우선순위 변경 로직 수정
  frontend/src/components/backlog/EpicDropdown.tsx
  frontend/src/pages/backlog/UnfinishedStoryPage.tsx
  frontend/src/utils/getDragElementIndex.ts
  frontend/src/utils/getNewColor.ts
Labels: FE, 🔨fix

#325 feaT: 태스크 드래그 앤 드롭 기능 구현
  frontend/src/components/backlog/StoryBlock.tsx
  frontend/src/components/backlog/StoryDragContainer.tsx
  frontend/src/components/backlog/TaskDragContainer.tsx
  frontend/src/hooks/pages/backlog/useBacklogSocket.ts
  frontend/src/pages/backlog/EpicPage.tsx
  frontend/src/pages/backlog/FinishedStoryPage.tsx
  frontend/src/pages/backlog/UnfinishedStoryPage.tsx
Labels: FE, 🎉feature

#327 feat: 에픽별 페이지 드래그 앤 드롭 기능 구현
  frontend/src/components/backlog/EpicBlock.tsx
  frontend/src/components/backlog/EpicDragContainer.tsx
  frontend/src/components/backlog/EpicPageStoryDragContainer.tsx
  frontend/src/components/backlog/EpicPageTaskDragContainer.tsx
  frontend/src/components/backlog/StoryBlock.tsx
  frontend/src/hooks/pages/backlog/useBacklogSocket.ts
  frontend/src/hooks/pages/backlog/useEpicEmitEvent.ts
  frontend/src/pages/backlog/EpicPage.tsx
  frontend/src/pages/backlog/FinishedStoryPage.tsx
  frontend/src/pages/backlog/UnfinishedStoryPage.tsx
Labels: FE, 🎉feature

#328 fix: 유효한 URL을 판별하는 정규식 수정
  backend/src/project/dto/link/LinkCreateRequest.dto.ts
  frontend/src/utils/isValidURL.ts
Labels: 🔨fix

#329 fix: 루트 페이지를 로그인 페이지로 변경, 플러스 아이콘 표시, 프로젝트 리스트 페이지 수정
  frontend/src/AppRouter.tsx
  frontend/src/components/account/TechStackInput.tsx
  frontend/src/components/projects/ProjectList.tsx
Labels: FE, 🔨fix
