Repository boostcampwm2023/web10-Lesser, pull requests merged in 2024-04, with the labels that each got.

#252 feat : PublicRouter, PrivateRouter 함수 개선
  frontend/src/AppRouter.tsx
  frontend/src/apis/api/loginAPI.ts
  frontend/src/apis/utils/authAPI.ts
  frontend/src/components/common/route/PrivateRoute.tsx
  frontend/src/components/common/route/PublicRoute.tsx
  frontend/src/utils/route/checkAuthentication.ts
Labels: FE, 🔨fix

#255 feat : 프로젝트 (메인 페이지) 사이드바 작성
  frontend/package.json
  frontend/src/AppRouter.tsx
  frontend/src/GlobalErrorBoundary.tsx
  frontend/src/assets/icons/backlog.svg
  frontend/src/assets/icons/chevron-right.svg
  frontend/src/assets/icons/landing.svg
  frontend/src/assets/icons/member.svg
  frontend/src/assets/icons/notifications.svg
  frontend/src/assets/icons/pageout.svg
  frontend/src/assets/icons/settings.svg
  frontend/src/assets/icons/sprint.svg
  frontend/src/components/main/PageIcon.tsx
  frontend/src/components/main/PageLinkIcons.tsx
  frontend/src/components/main/ProjectSidebar.tsx
  frontend/src/components/main/UtilIcons.tsx
  frontend/src/constants/path.ts
  frontend/src/pages/main/MainPage.tsx
  frontend/src/types/common.ts
  frontend/src/types/main.ts
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: FE, 🎉feature

#254 feat: 프로젝트 생성 페이지 UI 구현
  frontend/src/AppRouter.tsx
  frontend/src/components/account/NicknameInput.tsx
  frontend/src/components/account/PositionInput.tsx
  frontend/src/components/account/TechStackInput.tsx
  frontend/src/components/common/NextStepButton.tsx
  frontend/src/components/projects/ProjectCreateInput.tsx
  frontend/src/components/projects/ProjectCreateMainSection.tsx
  frontend/src/components/projects/ProjectCreateSideBar.tsx
  frontend/src/components/projects/index.ts
  frontend/src/constants/path.ts
  frontend/src/constants/projects.ts
  frontend/src/pages/index.ts
  frontend/src/pages/projects/ProjectCreatePage.tsx
  frontend/src/types/common.ts
Labels: FE, 🎉feature

#260 feat: 프로젝트 생성 API 연결 및 파비콘, 폰트 적용
  frontend/index.html
  frontend/package.json
  frontend/public/LesserLogo.png
  frontend/src/App.tsx
  frontend/src/apis/api/projectAPI.ts
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/components/projects/ProjectCard.tsx
  frontend/src/components/projects/ProjectCreateInput.tsx
  frontend/src/components/projects/ProjectCreateMainSection.tsx
  frontend/src/components/projects/ProjectList.tsx
  frontend/src/components/projects/ProjectsSideBar.tsx
  frontend/src/hooks/queries/project/index.ts
  frontend/src/hooks/queries/project/useGetProjects.ts
  frontend/src/hooks/queries/project/usePostCreateProject.ts
  frontend/src/index.css
  frontend/yarn.lock
Labels: FE, 🎉feature

#259 feat : Landing Page - ProjectUI, SprintUI, MemberUI 구현
  frontend/package.json
  frontend/src/AppRouter.tsx
  frontend/src/apis/api/loginAPI.ts
  frontend/src/apis/api/signupAPI.ts
  frontend/src/apis/utils/authAPI.ts
  frontend/src/components/common/ProfileImage.tsx
  frontend/src/components/common/route/PrivateRoute.tsx
  frontend/src/components/common/route/PublicRoute.tsx
  frontend/src/components/landing/LandingMember.tsx
  frontend/src/components/landing/LandingProject.tsx
  frontend/src/components/landing/LandingProjectLink.tsx
  frontend/src/components/landing/LandingSprint.tsx
  frontend/src/components/landing/LandingSprintBar.tsx
  frontend/src/components/landing/UserBlock.tsx
  frontend/src/components/main/PageIcon.tsx
  frontend/src/components/main/PageLinkIcons.tsx
  frontend/src/components/main/ProjectSidebar.tsx
  frontend/src/components/main/UtilIcons.tsx
  frontend/src/components/projects/ProjectCard.tsx
  frontend/src/components/projects/ProjectCreateInput.tsx
  frontend/src/components/projects/ProjectCreateMainSection.tsx
  frontend/src/components/projects/ProjectCreateSideBar.tsx
  frontend/src/components/projects/ProjectList.tsx
  frontend/src/components/projects/ProjectsSideBar.tsx
  frontend/src/constants/landing.ts
  frontend/src/hooks/common/dropdown/useDropdown.tsx
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/pages/main/MainPage.tsx
  frontend/src/pages/projects/ProjectCreatePage.tsx
  frontend/src/test/diffBetweenDate.test.ts
  frontend/src/test/projectSortingTest.test.tsx
  frontend/src/types/DTO/authDTO.ts
  frontend/src/types/DTO/landingDTO.ts
  frontend/src/types/DTO/projectDTO.ts
  frontend/src/types/common/common.ts
  frontend/src/types/common/main.ts
  frontend/src/utils/diffBetweenDate.ts
  frontend/src/utils/projectSortByOption.ts
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: FE, 🎉feature

#264 fix: socket.io path추가
  backend/src/project/websocket.gateway.ts
  backend/test/project/ws-project-landing-page.e2e-spec.ts
Labels: BE, 🔨fix, 🍐pair programming

#263 feat: 클라이언트 소켓 연결, 프로젝트 페이지 데이터 연동
  frontend/package.json
  frontend/src/components/landing/LandingMember.tsx
  frontend/src/components/projects/ProjectList.tsx
  frontend/src/constants/landing.ts
  frontend/src/hooks/common/socket/useLandingSocket.ts
  frontend/src/hooks/common/socket/useSocket.ts
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/pages/main/MainPage.tsx
  frontend/src/types/DTO/landingDTO.ts
  frontend/yarn.lock
Labels: FE, 🎉feature, 🍐pair programming

#265 fix: 프로젝트 생성, 회원 가입 페이지 버그 해결, 데모 피드백 반영
  frontend/src/components/account/NicknameInput.tsx
  frontend/src/components/account/PositionInput.tsx
  frontend/src/components/account/SignupMainSection.tsx
  frontend/src/components/account/TechStackInput.tsx
  frontend/src/components/common/CategoryButton.tsx
  frontend/src/components/common/NextStepButton.tsx
  frontend/src/components/landing/LandingProject.tsx
  frontend/src/components/projects/ProjectCreateInput.tsx
  frontend/src/components/projects/ProjectCreateMainSection.tsx
  frontend/src/components/projects/ProjectsSideBar.tsx
  frontend/src/constants/projects.ts
  frontend/src/pages/account/SignupPage.tsx
  frontend/src/pages/projects/ProjectCreatePage.tsx
Labels: FE, 🔨fix

#271 refactor: 프로젝트 addMember 서비스의 매개변수를 projectLinkId → project로 변경
  backend/src/project/project.controller.ts
  backend/src/project/service/project.service.spec.ts
  backend/src/project/service/project.service.ts
Labels: BE, ♻️ refactor

#269 feat: 임시 초대 페이지 생성 및 참가 API 연결
  frontend/src/AppRouter.tsx
  frontend/src/apis/api/loginAPI.ts
  frontend/src/apis/api/projectAPI.ts
  frontend/src/components/account/SignupMainSection.tsx
  frontend/src/components/common/route/PublicRoute.tsx
  frontend/src/components/landing/LandingMember.tsx
  frontend/src/constants/path.ts
  frontend/src/constants/storageKey.ts
  frontend/src/hooks/common/socket/useLandingSocket.ts
  frontend/src/pages/TempHomepage.tsx
  frontend/src/pages/invite/InvitePage.tsx
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/types/DTO/landingDTO.ts
Labels: FE, 🎉feature

#270 feat: 서버 socket.io 인증, 인가 구현
  backend/src/project/service/project.service.ts
  backend/src/project/websocket.gateway.ts
  backend/test/project/join-project.e2e-spec.ts
  backend/test/project/ws-connection.e2e-spec.ts
  backend/test/project/ws-project-landing-page.e2e-spec.ts
  backend/test/setup.ts
Labels: BE, 🎉feature, 🍐pair programming
