Repository boostcampwm2023/web10-Lesser, pull requests merged in 2024-06, with the labels that each got.

#287 feat: 프로젝트 참여시 랜딩페이지에 접속한 회원에게 새로운 회원의 정보를 알리는 API 구현
  backend/src/project/project.controller.ts
  backend/src/project/websocket.gateway.ts
  backend/test/project/ws-common.ts
  backend/test/project/ws-join-project.e2e-spec.ts
  backend/test/setup.ts
Labels: BE, 🎉feature

#284 refactor: 회원가입 페이지 애니메이션 및 구조 리팩토링
  frontend/src/components/account/PositionInput.tsx
  frontend/src/components/account/SignupMainSection.tsx
  frontend/src/components/account/TechStackInput.tsx
  frontend/src/components/account/TechStackModal.tsx
  frontend/src/components/account/UsernameInput.tsx
  frontend/src/components/common/CreateMainSection.tsx
  frontend/src/constants/account.ts
  frontend/src/hooks/common/dropdown/useDropdown.tsx
  frontend/src/hooks/common/useWheelDownActive.ts
  frontend/src/hooks/pages/account/useSignupForm.ts
  frontend/src/hooks/pages/account/useWheelDown.ts
  frontend/src/hooks/pages/account/useWheelUp.ts
  frontend/src/pages/account/SignupPage.tsx
Labels: FE, ♻️ refactor

#290 refactor : 서버에서 전달하는 데이터를 받아서 화면에 색상을 반영하는 코드 작성
  frontend/src/hooks/common/landing/useLandingMemo.tsx
  frontend/src/hooks/common/socket/useLandingSocket.ts
Labels: FE, ♻️ refactor

#289 feat: 프로젝트의 인원이 10명 이상일때, 새로운 인원이 참여하지 못하게하는 API 구현
  backend/src/project/project.controller.ts
  backend/src/project/service/project.service.spec.ts
  backend/src/project/service/project.service.ts
  backend/test/project/join-project.e2e-spec.ts
Labels: BE, 🎉feature

#292 refactor : Landing 페이지 데이터 구조 및 렌더링 최적화 리펙토링
  frontend/src/components/landing/common/LandingTitleUI.tsx
  frontend/src/components/landing/link/LandingLink.tsx
  frontend/src/components/landing/memo/LandingMemoList.tsx
  frontend/src/components/landing/memo/MemoBlock.tsx
  frontend/src/components/landing/memo/MemoColorButton.tsx
  frontend/src/components/landing/memo/MemoEditor.tsx
  frontend/src/components/landing/project/LandingProject.tsx
  frontend/src/components/landing/sprint/LandingSprint.tsx
  frontend/src/constants/landing.ts
  frontend/src/hooks/common/landing/useLandingLinkSocket.ts
  frontend/src/hooks/common/landing/useLandingMemo.tsx
  frontend/src/hooks/common/landing/useLandingMemoEditor.ts
  frontend/src/hooks/common/landing/useLandingMemoSocket.ts
  frontend/src/hooks/common/landing/useLandingProjectSocket.ts
  frontend/src/hooks/common/landing/useLandingSprintSocket.ts
  frontend/src/hooks/common/socket/useLandingEmitEvent.ts
  frontend/src/pages/landing/LandingPage.tsx
Labels: FE, 🔨fix, ♻️ refactor

#293 feat: 멤버 상태 변경 기능
  frontend/package.json
  frontend/src/components/landing/member/LandingMember.tsx
  frontend/src/hooks/common/dropdown/useDropdown.tsx
  frontend/src/hooks/common/landing/useLandingLinkSocket.ts
  frontend/src/hooks/common/landing/useLandingMemoSocket.ts
  frontend/src/hooks/common/landing/useLandingProjectSocket.ts
  frontend/src/hooks/common/landing/useLandingSprintSocket.ts
  frontend/src/hooks/common/member/useAwayUser.ts
  frontend/src/hooks/common/member/useUpdateUserStatus.ts
  frontend/src/hooks/common/member/useUserLeaveProject.ts
  frontend/src/hooks/common/socket/useLandingSocket.ts
  frontend/src/hooks/common/socket/useSocket.ts
  frontend/src/hooks/common/throttle/useThrottle.ts
  frontend/src/pages/landing/LandingPage.tsx
  frontend/src/pages/main/MainPage.tsx
  frontend/src/stores/useMemberStore.ts
  frontend/src/types/common/landing.ts
  frontend/src/utils/emitMemberStatusUpdate.ts
  frontend/yarn.lock
Labels: FE, 🎉feature

#294 refactor: 프로젝트 생성 페이지 애니메이션 리팩토링
  frontend/src/components/projects/ProjectCard.tsx
  frontend/src/components/projects/ProjectCreateInput.tsx
  frontend/src/components/projects/ProjectCreateMainSection.tsx
  frontend/src/components/projects/ProjectCreateSideBar.tsx
  frontend/src/constants/projects.ts
  frontend/src/hooks/pages/project/useCreateProjectForm.ts
  frontend/src/pages/projects/ProjectCreatePage.tsx
Labels: FE, ♻️ refactor

#295 fix: 처음 접속 시 서버에서 보내준 상태 반영, 여러 탭 사용 시 수동 자리비움 상태 변경 동작 모두 적용
  frontend/src/components/landing/member/LandingMember.tsx
  frontend/src/components/landing/member/UserBlock.tsx
  frontend/src/constants/storageKey.ts
  frontend/src/hooks/common/member/useAwayUser.ts
  frontend/src/hooks/common/member/useUpdateUserStatus.ts
  frontend/src/hooks/common/socket/useLandingSocket.ts
  frontend/src/test/sortMemberByStatus.test.ts
  frontend/src/utils/sortMemberByStatus.ts
Labels: 🔨fix, 🎉feature

#300 feat: 10명 이상 프로젝트 에러 처리
  frontend/src/pages/invite/InvitePage.tsx
Labels: FE, 🎉feature
